server:
  port: 8080

spring:
  application:
    name: api-consumer
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: banks
          uri: http://localhost:8081
          predicates:
            - Path=/api/banks/**
        - id: accounts
          uri: http://localhost:8082
          predicates:
            - Path=/api/accounts/**
